In [62]:
import pandas
import numpy
from sklearn import neighbors
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score as cvs
from sklearn import tree
from sklearn import ensemble

In [3]:
iris = pandas.read_csv('iris.csv')
iris.sample(5)

id  sepal_length  sepal_width  petal_length  petal_width  \
98    99           5.1          2.5           3.0          1.1   
117  118           7.7          3.8           6.7          2.2   
59    60           5.2          2.7           3.9          1.4   
53    54           5.5          2.3           4.0          1.3   
96    97           5.7          2.9           4.2          1.3   

             species  
98   Iris-versicolor  
117   Iris-virginica  
59   Iris-versicolor  
53   Iris-versicolor  
96   Iris-versicolor

In [94]:
#knn逻辑回归
knn = neighbors.KNeighborsClassifier(10,weights='uniform')
feature = ['petal_length','petal_width','sepal_length','sepal_width']
X = iris[feature]
#离散型转数值型
le = LabelEncoder()
le.fit(iris['species'])
y = le.transform(iris['species'])
print(y)
model = knn.fit(X,y)
scores = cvs(knn,X,y,cv=5,scoring='accuracy')
score = numpy.mean(scores)
print(score)
model.predict([[1,1,1,1]])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
0.98


array([0], dtype=int64)

In [58]:
#knn线性回归
knn = neighbors.KNeighborsRegressor(5,weights='uniform')
feature = ['petal_length','petal_width','sepal_length','sepal_width']
X = iris[feature]
#离散型转数值型
le = LabelEncoder()
le.fit(iris['species'])
y = le.transform(iris['species'])
print(y)
model = knn.fit(X,y)
scores = -cvs(knn,X,y,cv=5,scoring='neg_mean_squared_error')
score = numpy.mean(scores)
print(score)
model.predict([[5,5,5,5]])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
0.0717333333333


array([ 2.])

In [54]:
#决策树逻辑回归
dt = tree.DecisionTreeClassifier()
feature = ['petal_length','petal_width','sepal_length','sepal_width']
X = iris[feature]
#离散型转数值型
le = LabelEncoder()
le.fit(iris['species'])
y = le.transform(iris['species'])
print(y)
model = dt.fit(X,y)
scores = cvs(dt,X,y,cv=5,scoring='accuracy')
score = numpy.mean(scores)
print(score)
model.predict([[5,5,5,5]])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
0.966666666667


array([2], dtype=int64)

In [64]:
#决策树线性回归
dt = tree.DecisionTreeRegressor()
feature = ['petal_length','petal_width','sepal_length','sepal_width']
X = iris[feature]
#离散型转数值型
le = LabelEncoder()
le.fit(iris['species'])
y = le.transform(iris['species'])
print(y)
model = dt.fit(X,y)
scores = -cvs(dt,X,y,cv=5,scoring='neg_mean_squared_error')
score = numpy.mean(scores)
print(score)
model.predict([[5,5,5,5]])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
0.08


array([ 2.])

In [91]:
#随机森林逻辑回归
rf = ensemble.RandomForestClassifier(8)
feature = ['sepal_length','sepal_width','petal_length','petal_width']
X = iris[feature]
#离散型转数值型
le = LabelEncoder()
le.fit(iris['species'])
y = le.transform(iris['species'])
print(y)
model = dt.fit(X,y)
scores = cvs(rf,X,y,cv=5,scoring='accuracy')
score = numpy.mean(scores)
print(score)
model.predict([[7.7,3.8,6.7,2.2]])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
0.953333333333


array([ 2.])

In [90]:
#随机森林线性回归
rf = ensemble.RandomForestRegressor(8)
feature = ['sepal_length','sepal_width','petal_length','petal_width']
X = iris[feature]
#离散型转数值型
le = LabelEncoder()
le.fit(iris['species'])
y = le.transform(iris['species'])
print(y)
model = dt.fit(X,y)
scores = -cvs(rf,X,y,cv=5,scoring='neg_mean_squared_error')
score = numpy.mean(scores)
print(score)
model.predict([[5.2,2.7,3.9,1.4]])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
0.0660416666667


array([ 1.])